name: Worflow TU

on: [pull_request]

jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: recup du repo
        uses: actions/checkout@v2
      - name: éxecution des tests
        run: npm test