name: Worflow docker

on: [push]

jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: recup du repo
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
      - name: dependances
        run: npm install
      - name: éxecution des tests
        run: npm test

  docker:
      runs-on: ubuntu-latest
      steps:
        - name: Récuperation du repo
          uses: actions/checkout@v2
        - name: Install QEMU Docker
          uses: docker/setup-qemu-action@v1
        - name: Install BuildX docker
          uses: docker/setup-buildx-action@v1
        - name: Connection à docker
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: build et push mon image docker
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: elvis1971/weather:latest




    