name: Worflow TU

on: [push]

jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: recup du repo
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
      - name: dependances
        run: npm install
      - name: éxecution des tests
        run: npm test